# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('external_c', models.IntegerField()),
                ('internal_c', models.IntegerField()),
                ('wind_kph', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('chance_of_precipitation', models.IntegerField()),
                ('expected_high', models.IntegerField()),
                ('expected_low', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boiler_high', models.IntegerField()),
                ('boiler_low', models.IntegerField()),
                ('margin_of_error', models.IntegerField()),
                ('ideal_temp', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
