# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
