# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='external_c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='internal_c',
            field=models.FloatField(),
        ),
    ]
