# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_remove_user_setting_margin_of_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_setting',
            name='ideal_temp',
        ),
        migrations.AddField(
            model_name='user_setting',
            name='setting',
            field=models.CharField(choices=[(b'ECONOMICAL', b'Economical'), (b'COMFORT', b'Comfort')], default=b'COMFORT', max_length=10),
        ),
    ]
