# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_auto_20170308_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_setting',
            name='ideal_temp',
            field=models.IntegerField(default=19),
        ),
    ]
