# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_user_setting_ideal_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_setting',
            name='system_override',
            field=models.BooleanField(default=False),
        ),
    ]
