# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_user_setting_system_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snow_expected', models.BooleanField(default=False)),
                ('ice_expected', models.BooleanField(default=False)),
                ('heatwave_expected', models.BooleanField(default=False)),
                ('open_windows', models.BooleanField(default=False)),
            ],
        ),
    ]
