# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='heating_system',
            name='hours_remaining',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
