# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_heating_system_hours_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heating_system',
            name='hours_remaining',
        ),
    ]
